<fieldset class="form-list">
    <?php	    
        $_code=$this->getMethodCode();
        $max_installments = $this->getMaxInstallments();
        $installments_options = $this->getInstallmentsOptions($max_installments);
    ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
	<?php	
		if($max_installments > 1) {
			$selectNum = $this->__('Select number of installments');
			$pleaseSelect =  $this->__('Please Select');
			echo '		
			<li>
			  <div class="generic-select-input input-box">
				  <label for="' . $_code . '_installments">'. $selectNum . '</label><br />
				  <select id="' . $_code . '_installments" name="payment[installments]">
					<option selected="selected">1</option>';
					  foreach($installments_options as $option) {
						echo '<option value="' . $option . '">' . $option . '</option>';
					}
		echo     '</select>
			  </div>
			</li>';
		}
	?>
        <li>
            <?php echo $this->__('You will be redirected to Alpha e-Commerce website when you place an order.') ?>
        </li>
    </ul>
</fieldset>
